#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LojaVirtual.Resource", IsApplication=true)]

namespace LojaVirtual
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ljv = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int linearLayout2 = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout3 = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class IdAcessar
		{
			
			// aapt resource value: 0x7f070007
			public const int btnAcessar = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int btnCadastrar = 2131165192;
			
			// aapt resource value: 0x7f070002
			public const int lblMensagem = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int tvEmail = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int tvSenha = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int tvTitulo = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int txtEmail = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int txtSenha = 2131165190;
			
			static IdAcessar()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private IdAcessar()
			{
			}
		}
		
		public partial class IdCadastro
		{
			
			// aapt resource value: 0x7f080014
			public const int btnSalvar = 2131230740;
			
			// aapt resource value: 0x7f080004
			public const int lblCPF = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int lblCadastro = 2131230722;
			
			// aapt resource value: 0x7f080008
			public const int lblEmail = 2131230728;
			
			// aapt resource value: 0x7f080010
			public const int lblEndereco = 2131230736;
			
			// aapt resource value: 0x7f08000c
			public const int lblEstado = 2131230732;
			
			// aapt resource value: 0x7f080003
			public const int lblMensagem = 2131230723;
			
			// aapt resource value: 0x7f08000e
			public const int lblMunicipio = 2131230734;
			
			// aapt resource value: 0x7f080006
			public const int lblNome = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int lblSenha = 2131230730;
			
			// aapt resource value: 0x7f080012
			public const int lblTelefone = 2131230738;
			
			// aapt resource value: 0x7f080001
			public const int lblTitulo = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int llTitulo = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int txtCPF = 2131230725;
			
			// aapt resource value: 0x7f080009
			public const int txtEmail = 2131230729;
			
			// aapt resource value: 0x7f080011
			public const int txtEndereco = 2131230737;
			
			// aapt resource value: 0x7f08000d
			public const int txtEstado = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int txtMunicipio = 2131230735;
			
			// aapt resource value: 0x7f080007
			public const int txtNome = 2131230727;
			
			// aapt resource value: 0x7f08000b
			public const int txtSenha = 2131230731;
			
			// aapt resource value: 0x7f080013
			public const int txtTelefone = 2131230739;
			
			static IdCadastro()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private IdCadastro()
			{
			}
		}
		
		public partial class IdConta
		{
			
			// aapt resource value: 0x7f090018
			public const int btnExcluir = 2131296280;
			
			// aapt resource value: 0x7f090017
			public const int btnSalvar = 2131296279;
			
			// aapt resource value: 0x7f090003
			public const int hfDataCadastro = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int hfIdConta = 2131296258;
			
			// aapt resource value: 0x7f090006
			public const int lblCPF = 2131296262;
			
			// aapt resource value: 0x7f09000a
			public const int lblEmail = 2131296266;
			
			// aapt resource value: 0x7f090012
			public const int lblEndereco = 2131296274;
			
			// aapt resource value: 0x7f09000e
			public const int lblEstado = 2131296270;
			
			// aapt resource value: 0x7f090005
			public const int lblMensagem = 2131296261;
			
			// aapt resource value: 0x7f090010
			public const int lblMunicipio = 2131296272;
			
			// aapt resource value: 0x7f090008
			public const int lblNome = 2131296264;
			
			// aapt resource value: 0x7f09000c
			public const int lblSenha = 2131296268;
			
			// aapt resource value: 0x7f090014
			public const int lblTelefone = 2131296276;
			
			// aapt resource value: 0x7f090016
			public const int llBotoes = 2131296278;
			
			// aapt resource value: 0x7f090000
			public const int llTituloApp = 2131296256;
			
			// aapt resource value: 0x7f090004
			public const int tvPaginaTitulo = 2131296260;
			
			// aapt resource value: 0x7f090001
			public const int tvTitulo = 2131296257;
			
			// aapt resource value: 0x7f090007
			public const int txtCPF = 2131296263;
			
			// aapt resource value: 0x7f09000b
			public const int txtEmail = 2131296267;
			
			// aapt resource value: 0x7f090013
			public const int txtEndereco = 2131296275;
			
			// aapt resource value: 0x7f09000f
			public const int txtEstado = 2131296271;
			
			// aapt resource value: 0x7f090011
			public const int txtMunicipio = 2131296273;
			
			// aapt resource value: 0x7f090009
			public const int txtNome = 2131296265;
			
			// aapt resource value: 0x7f09000d
			public const int txtSenha = 2131296269;
			
			// aapt resource value: 0x7f090015
			public const int txtTelefone = 2131296277;
			
			static IdConta()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private IdConta()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Acessar = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Cadastrar = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Conta = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ljv = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
